spring:
  application:
    name: user-service

server:
  port: 8080

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/

comet:
  file-component:
    clients:
      share:
        protocol: share
        working-directory-in-server: /Users/hubery/git/springcloud-demo1/user-service/src/test/resources
      sftp:
        protocol: sftp
        working-directory-in-server: upload
        sftp:
          host: 127.0.0.1
          port: 22
          username: sftp
          password: 123456
      ftp:
        protocol: ftp
        ftp:
          host: 127.0.0.1
          port: 21
          username: hubery
          password: 123456
      #      scene-accounting:
      default:
        protocol: oss
        oss:
          endpoint: oss-cn-chengdu.aliyuncs.com
          access-key-id: <KEY>
          access-key-secret: <KEY>
          # 绝大部分情况下，一个业务系统只需要访问一个bucket，调用文件上传和下载接口时，可以不指定 bucket，会自动使用这里配置的默认 bucket。如果一个业务系统需要访问多个不同的bucket，那么需要在调用接口时指定 bucket。
          default-bucket: hubery-oss-demo
          # 是否启用断点续传，默认关闭
          enable-checkpoint: false
          # 分片上传和下载配置，可以通过将分片大小设的足够大来禁用分片
          multipart:
            # 分片大小，单位：字节，默认100K，即102400
            part-size: 10485760
            # 分片上传或下载时的并发线程数，默认为 1
            task-num: 10
      scene-plan:
        protocol: oss
        oss:
          endpoint: oss-cn-beijing.aliyuncs.com
          access-key-id: <KEY>
          access-key-secret: <KEY>
          # 绝大部分情况下，一个业务系统只需要访问一个bucket，调用文件上传和下载接口时，可以不指定 bucket，会自动使用这里配置的默认 bucket。如果一个业务系统需要访问多个不同的bucket，那么需要在调用接口时指定 bucket。
          default-bucket: bucket2
          # 是否启用断点续传，默认关闭
          enable-checkpoint: false
          # 分片上传和下载配置，可以通过将分片大小设的足够大来禁用分片
          multipart:
            # 分片大小，单位：字节，默认100K，即102400
            part-size: 10485760
            # 分片上传或下载时的并发线程数，默认为 1
            task-num: 10
      scene-whitelist:
        protocol: sftp
        sftp:
          host: 127.0.0.1
          port: 22
          username: hubery
          password: 123456
logging:
  level:
    root: info
    pers.hubery: debug